#!/usr/bin/env -S uv run -s
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "fire>=0.6",
#   "httpx>=0.27",
#   "loguru",
#   "numpy",
#   "openai>=1.50",
#   "pillow",
#   "python-slugify>=8",
#   "pyyaml",
#   "rich>=13",
#   "tenacity",
#   "webcolors",
# ]
# ///
# this_file: tools/generate_illu.py

"""Generate three mid-century single-line illustrations per blog post.

For every post in src_docs/md/posts/*.md, three variants are produced:
  {slug}-1.png  literal     direct, recognisable interpretation of the title
  {slug}-2.png  abstract    symbolic / conceptual interpretation
  {slug}-3.png  humorous    witty, unexpected riff on a phrase from the body

The image is generated by :mod:`imgquotio` and post-processed by
:mod:`imgopti` into compact black-on-transparent PNGs (then ``pngquant``-ed
if available). Async with bounded concurrency, tenacity retries, skip-existing.
"""

from __future__ import annotations

import asyncio
import re
import sys
from pathlib import Path

import fire
import yaml
from loguru import logger
from tenacity import (
    AsyncRetrying,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

# Sibling-script imports — both live in tools/ alongside this file.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from imgopti import optimize_inplace  # noqa: E402
from imgquotio import generate as imgquotio_generate  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
POSTS = ROOT / "src_docs/md/posts"
DEFAULT_OUT = ROOT / "src_docs/md/media/illu"

DEFAULT_CONCURRENCY = 3
DEFAULT_MODEL = "gpt"

STYLE = (
    "Saul Steinberg / Paul Rand single-weight pen-line illustration. ONE "
    "continuous loose ink line drawing on a PLAIN WHITE BACKGROUND. Pure "
    "black ink line only — no fill, no shading, no halftone, no hatching, no "
    "color, no gray, no texture, no paper grain, no border, no signature, no "
    "text. The line is confident, slightly imperfect, hand-drawn, charming, "
    "economical. Generous negative space. Composition fills the square but "
    "keeps the subject central with breathing room. Square 1024x1024. The "
    "result must read as iconic at thumbnail size and retain charm at full "
    "size. NEVER include any letter, word, label, or signature in the image."
)

MODES: dict[str, str] = {
    "1": (
        "DIRECT / LITERAL interpretation. Draw the post's subject "
        "recognisably and clearly, but reduced to its iconic essence in a "
        "single witty pen line. The viewer should immediately recognise WHAT "
        "the post is about."
    ),
    "2": (
        "ABSTRACT / SYMBOLIC interpretation. Translate the post's underlying "
        "idea into a metaphor, a gesture, or a symbol — never literal. Quiet, "
        "lyrical, slightly mysterious. The viewer should sense the MOOD of "
        "the post."
    ),
    "3": (
        "HUMOROUS / UNEXPECTED riff. A small visual joke, pun, or surreal "
        "twist on a specific phrase from the post. Charming, slightly absurd, "
        "Steinberg-style wit. The viewer should smile."
    ),
}


def parse_post(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, flags=re.DOTALL)
    if not m:
        return path.stem, ""
    fm = yaml.safe_load(m.group(1)) or {}
    title = str(fm.get("title", path.stem))
    body = m.group(2).strip()
    chunks: list[str] = []
    for line in body.splitlines():
        s = line.strip()
        if s and not s.startswith(("#", "!", "[", "<", "```", "---")):
            chunks.append(s)
        if sum(len(c) for c in chunks) > 320:
            break
    blurb = re.sub(r"\s+", " ", " ".join(chunks))[:400]
    return title, blurb


def slug_for(path: Path) -> str:
    return re.sub(r"^\d{4}-\d{2}-\d{2}-", "", path.stem)


def build_prompt(mode: str, title: str, blurb: str) -> str:
    direction = MODES[mode]
    if mode == "3":
        anchor = (
            f"Pick ONE small concrete phrase, image, or word from this excerpt "
            f"and riff on it visually: \"{blurb}\""
        )
    else:
        anchor = (
            f"Subject of the post: \"{title}\". Background context (do not "
            f"depict literally): {blurb}"
        )
    return f"{STYLE} {direction} {anchor}"


async def gen_one(
    sem: asyncio.Semaphore,
    path: Path,
    mode: str,
    idx: int,
    total: int,
    *,
    color: str,
    quantize: bool,
    model: str,
    out_dir: Path,
) -> bool:
    slug = slug_for(path)
    out = out_dir / f"{slug}-{mode}.png"
    if out.exists() and out.stat().st_size > 4000:
        logger.info(f"[{idx}/{total}] SKIP {out.name}")
        return True
    title, blurb = parse_post(path)
    prompt = build_prompt(mode, title, blurb)

    def _log_retry(retry_state) -> None:
        exc = retry_state.outcome.exception() if retry_state.outcome else None
        logger.warning(
            f"[{idx}/{total}] FAIL {out.name} attempt "
            f"{retry_state.attempt_number}/3: {type(exc).__name__}: {exc}"
        )

    async with sem:
        try:
            async for attempt in AsyncRetrying(
                stop=stop_after_attempt(3),
                wait=wait_exponential(multiplier=2, min=4, max=30),
                retry=retry_if_exception_type(Exception),
                before_sleep=_log_retry,
                reraise=True,
            ):
                with attempt:
                    logger.info(f"[{idx}/{total}] GEN  {out.name}  ({title[:50]})")
                    paths = await asyncio.to_thread(
                        imgquotio_generate,
                        prompt,
                        output=str(out),
                        model=model,
                        size="1024x1024",
                    )
                    if not paths or not paths[0].exists() or paths[0].stat().st_size < 4000:
                        size = paths[0].stat().st_size if paths and paths[0].exists() else 0
                        raise RuntimeError(
                            f"imgquotio produced no usable file for {out.name} "
                            f"(paths={paths}, size={size} bytes)"
                        )
                    await asyncio.to_thread(
                        optimize_inplace, paths[0], color=color, quantize=quantize
                    )
                    size_kb = paths[0].stat().st_size // 1024
                    logger.success(f"[{idx}/{total}] OK   {out.name} ({size_kb} KB)")
                    return True
        except Exception as e:
            logger.exception(
                f"[{idx}/{total}] GIVE-UP {out.name} after 3 attempts: "
                f"{type(e).__name__}: {e}"
            )
            return False
    return False


async def _run(
    *, color: str, quantize: bool, concurrency: int, model: str, out_dir: Path
) -> int:
    posts = sorted(POSTS.glob("*.md"))
    if not posts:
        logger.error(f"No posts found in {POSTS}")
        return 1
    out_dir.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(concurrency)
    jobs: list[tuple[Path, str]] = [(p, m) for p in posts for m in ("1", "2", "3")]
    total = len(jobs)
    tasks = [
        asyncio.create_task(
            gen_one(
                sem, p, m, i + 1, total,
                color=color, quantize=quantize, model=model, out_dir=out_dir,
            )
        )
        for i, (p, m) in enumerate(jobs)
    ]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    ok = sum(1 for r in results if r is True)
    fail = total - ok
    logger.info(f"Done: {ok}/{total} ok, {fail} failed")
    return 0 if fail == 0 else 2


def cli(
    color: str = "black",
    quantize: bool = True,
    concurrency: int = DEFAULT_CONCURRENCY,
    model: str = DEFAULT_MODEL,
    out_dir: str | Path | None = None,
) -> None:
    """Generate all three illustration variants for every post.

    Args:
        color: Ink color for the post-processed PNG (CSS name, hex, or RGB tuple).
        quantize: Run pngquant after PIL save (no-op if pngquant is missing).
        concurrency: Number of in-flight generations (image API rate-limited).
        model: imgquotio model identifier (e.g. "gpt", "nano").
        out_dir: Output directory for PNGs (defaults to src_docs/md/media/illu).
    """
    out_path = Path(out_dir).expanduser().resolve() if out_dir else DEFAULT_OUT
    sys.exit(
        asyncio.run(
            _run(
                color=color,
                quantize=quantize,
                concurrency=concurrency,
                model=model,
                out_dir=out_path,
            )
        )
    )


if __name__ == "__main__":
    fire.Fire(cli)
