#!/usr/bin/env -S uv run -s
# /// script
# requires-python = ">=3.12"
# dependencies = ["tenacity", "pyyaml", "loguru", "Pillow"]
# ///
# this_file: tools/generate_illu.py
"""Generate 3 mid-century single-line illustrations per blog post.

For every post in src_docs/md/posts/*.md, three variants are produced:
  {slug}-1.png  literal     — direct, recognisable interpretation of the title
  {slug}-2.png  abstract    — symbolic / conceptual interpretation
  {slug}-3.png  humorous    — witty, unexpected riff on a phrase from the body

Each image is generated by imgquotio.py in the Saul Steinberg / Paul Rand
single-line aesthetic, then post-processed with Pillow into pure black line
art on a transparent background — luminance threshold drives alpha so the cream
paper falls away.

Async, three concurrent generations, tenacity retries, skip-existing.
"""

from __future__ import annotations

import asyncio
import re
import sys
from pathlib import Path

import yaml
from loguru import logger
from PIL import Image
from tenacity import (
    AsyncRetrying,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

ROOT = Path(__file__).resolve().parent.parent
POSTS = ROOT / "src_docs/md/posts"
OUT = ROOT / "src_docs/md/media/illu"
OUT.mkdir(parents=True, exist_ok=True)

CONCURRENCY = 3

# A locked-in mid-century single-line aesthetic. Identical preamble for every
# variant so the 333 images form ONE coherent visual language.
STYLE = (
    "Saul Steinberg / Paul Rand single-weight pen-line illustration. ONE "
    "continuous loose ink line drawing on a PLAIN WHITE BACKGROUND. Pure "
    "black ink line only — no fill, no shading, no halftone, no hatching, no "
    "color, no gray, no texture, no paper grain, no border, no signature, no "
    "text. The line is confident, slightly imperfect, hand-drawn, charming, "
    "economical. Generous negative space. Composition fills the square but "
    "keeps the subject central with breathing room. Square 1024x1024. The "
    "result must read as iconic at thumbnail size and retain charm at full "
    "size. NEVER include any letter, word, label, or signature in the image."
)

# Three different interpretation modes. Each adds a distinct creative direction
# on top of STYLE.
MODES: dict[str, str] = {
    "1": (
        "DIRECT / LITERAL interpretation. Draw the post's subject "
        "recognisably and clearly, but reduced to its iconic essence in a "
        "single witty pen line. The viewer should immediately recognise WHAT "
        "the post is about."
    ),
    "2": (
        "ABSTRACT / SYMBOLIC interpretation. Translate the post's underlying "
        "idea into a metaphor, a gesture, or a symbol — never literal. Quiet, "
        "lyrical, slightly mysterious. The viewer should sense the MOOD of "
        "the post."
    ),
    "3": (
        "HUMOROUS / UNEXPECTED riff. A small visual joke, pun, or surreal "
        "twist on a specific phrase from the post. Charming, slightly absurd, "
        "Steinberg-style wit. The viewer should smile."
    ),
}


def parse_post(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, flags=re.DOTALL)
    if not m:
        return path.stem, ""
    fm = yaml.safe_load(m.group(1)) or {}
    title = str(fm.get("title", path.stem))
    body = m.group(2).strip()
    # Collect first ~3 non-trivial sentences as humour-fodder
    chunks: list[str] = []
    for line in body.splitlines():
        s = line.strip()
        if s and not s.startswith(("#", "!", "[", "<", "```", "---")):
            chunks.append(s)
        if sum(len(c) for c in chunks) > 320:
            break
    blurb = " ".join(chunks)
    blurb = re.sub(r"\s+", " ", blurb)[:400]
    return title, blurb


def slug_for(path: Path) -> str:
    return re.sub(r"^\d{4}-\d{2}-\d{2}-", "", path.stem)


def build_prompt(mode: str, title: str, blurb: str) -> str:
    direction = MODES[mode]
    if mode == "3":
        anchor = (
            f"Pick ONE small concrete phrase, image, or word from this excerpt "
            f"and riff on it visually: \"{blurb}\""
        )
    else:
        anchor = (
            f"Subject of the post: \"{title}\". Background context (do not "
            f"depict literally): {blurb}"
        )
    return f"{STYLE} {direction} {anchor}"


def postprocess(path: Path) -> None:
    """Convert paper-toned line art into pure black line on transparent BG.

    Luminance drives alpha: dark pixels → opaque black, light pixels →
    transparent. A soft mid-band keeps anti-aliasing on the strokes.
    """
    with Image.open(path) as src:
        rgb = src.convert("RGB")
        w, h = rgb.size
        pixels = rgb.load()
        out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        op = out.load()
        # Tunable thresholds. Strokes should be near-black; paper near-white.
        # Anything darker than DARK_LIMIT → fully opaque black; lighter than
        # LIGHT_LIMIT → fully transparent; in-between → linear ramp for AA.
        DARK_LIMIT = 60
        LIGHT_LIMIT = 200
        span = max(LIGHT_LIMIT - DARK_LIMIT, 1)
        for y in range(h):
            for x in range(w):
                r, g, b = pixels[x, y]
                lum = 0.299 * r + 0.587 * g + 0.114 * b
                if lum <= DARK_LIMIT:
                    op[x, y] = (0, 0, 0, 255)
                elif lum >= LIGHT_LIMIT:
                    op[x, y] = (0, 0, 0, 0)
                else:
                    alpha = int(255 * (LIGHT_LIMIT - lum) / span)
                    op[x, y] = (0, 0, 0, alpha)
        out.save(path, "PNG", optimize=True)


async def gen_one(
    sem: asyncio.Semaphore,
    path: Path,
    mode: str,
    idx: int,
    total: int,
) -> bool:
    slug = slug_for(path)
    out = OUT / f"{slug}-{mode}.png"
    if out.exists() and out.stat().st_size > 4000:
        logger.info(f"[{idx}/{total}] SKIP {out.name}")
        return True
    title, blurb = parse_post(path)
    prompt = build_prompt(mode, title, blurb)

    async with sem:
        async for attempt in AsyncRetrying(
            stop=stop_after_attempt(3),
            wait=wait_exponential(multiplier=2, min=4, max=30),
            retry=retry_if_exception_type(Exception),
            reraise=True,
        ):
            with attempt:
                logger.info(f"[{idx}/{total}] GEN  {out.name}  ({title[:50]})")
                proc = await asyncio.create_subprocess_exec(
                    "imgquotio.py",
                    prompt,
                    "--model",
                    "gpt",
                    "--output",
                    str(out),
                    "--size",
                    "1024x1024",
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _, stderr = await proc.communicate()
                if proc.returncode != 0 or not out.exists() or out.stat().st_size < 4000:
                    err = stderr.decode("utf-8", errors="replace")[-300:]
                    raise RuntimeError(f"imgquotio failed for {out.name}: {err}")
                # Post-process to black-on-transparent. Run in thread so we
                # don't block the event loop.
                await asyncio.to_thread(postprocess, out)
                logger.success(
                    f"[{idx}/{total}] OK   {out.name} ({out.stat().st_size // 1024} KB)"
                )
                return True
    return False


async def main() -> int:
    posts = sorted(POSTS.glob("*.md"))
    if not posts:
        logger.error(f"No posts found in {POSTS}")
        return 1
    sem = asyncio.Semaphore(CONCURRENCY)
    jobs: list[tuple[Path, str]] = []
    for p in posts:
        for mode in ("1", "2", "3"):
            jobs.append((p, mode))
    total = len(jobs)
    tasks = [
        asyncio.create_task(gen_one(sem, p, m, i + 1, total))
        for i, (p, m) in enumerate(jobs)
    ]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    ok = sum(1 for r in results if r is True)
    fail = total - ok
    logger.info(f"Done: {ok}/{total} ok, {fail} failed")
    return 0 if fail == 0 else 2


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
